name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: discover storybook stories
        run: npm run storybook-discover
      - name: Run tests
        run: npm run test
